baseURL = "http://localhost:1313/"
enableRobotsTXT = true
languageCode = "en-us"
theme = "Custobar"
title = "Custobar "
[params]
metadescription = "Custobar"
sharedescription = "Custobar"
shareimage = "/uploads/2017/11/30/share.jpg"
sharetitle = "Custobar"
